create table Client
(
    client_id        bigint primary key generated by default as identity,
    last_name        varchar(30)  not null,
    first_name       varchar(30)  not null,
    middle_name      varchar(30),
    birth_date       date         not null,
    email            varchar(100) not null,
    gender           varchar(10),
    martial_status   varchar(13),
    dependent_amount int,
    passport_id      jsonb        not null,
    employment_id    jsonb,
    account          varchar(20)
);

create table Credit
(
    credit_id        bigint primary key generated by default as identity,
    amount           decimal check ( amount >= 10000 ) not null,
    term             int check ( term >= 6 )           not null,
    monthly_payment  decimal                           not null,
    rate             decimal                           not null,
    psk              decimal                           not null,
    payment_schedule jsonb                             not null,
    insurance_enable boolean                           not null,
    salary_client    boolean                           not null,
    credit_status    varchar(10)                       not null
);

create table Application
(
    application_id bigint primary key generated by default as identity,
    client_id      bigint    references Client (client_id) on delete set null,
    credit_id      bigint references Credit (credit_id) on delete cascade,
    status         varchar(17),
    creation_date  timestamp not null,
    applied_offer  jsonb,
    sign_date      timestamp,
    ses_code       varchar(100),
    status_history jsonb
)